In [1]:
import pandas
import seaborn
import numpy
import sklearn.preprocessing
import sklearn.feature_selection
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer

In [2]:
data_train = pandas.read_csv('../dataset/high_salary.train.csv').set_index('id')
data_train

,social-security-number,house-number,age-group,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native-country-code,native-country,label
id,,,,,,,,,,,,,,,,,,
2103,438607793.0,1341.0,2.0,self-emp-not-inc,335549.0,prof-school,15.0,never-married,prof-specialty,not-in-family,white,male,0.0,4.0,2.0,USA,united-states,1.0
14649,555786276.0,5891.0,0.0,private,98287.0,hs-grad,9.0,married-civ-spouse,sales,husband,white,male,0.0,0.0,3.0,USA,united-states,0.0
7379,350318677.0,4291.0,2.0,self-emp-not-inc,127740.0,hs-grad,9.0,married-civ-spouse,exec-managerial,husband,white,male,0.0,0.0,4.0,USA,united-states,0.0
24479,356142771.0,3392.0,2.0,self-emp-not-inc,48553.0,some-college,10.0,married-civ-spouse,craft-repair,husband,white,male,0.0,0.0,3.0,USA,united-states,0.0
19532,385803045.0,492.0,3.0,private,403061.0,1st-4th,2.0,never-married,machine-op-inspct,other-relative,white,female,0.0,0.0,2.0,MEX,mexico,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8695,181655516.0,361.0,0.0,private,42706.0,some-college,10.0,never-married,prof-specialty,not-in-family,white,male,0.0,0.0,2.0,USA,united-states,0.0
2192,796404433.0,950.0,2.0,local-gov,103759.0,some-college,10.0,married-civ-spouse,transport-moving,husband,white,male,2.0,0.0,2.0,USA,united-states,0.0
8250,622635909.0,8689.0,0.0,private,316184.0,hs-grad,9.0,never-married,other-service,other-relative,black,male,0.0,0.0,2.0,USA,united-states,0.0
18511,338364928.0,5238.0,2.0,private,481987.0,masters,14.0,married-civ-spouse,tech-support,husband,white,male,0.0,0.0,0.0,USA,united-states,1.0
16074,657404344.0,8745.0,2.0,self-emp-not-inc,75065.0,12th,8.0,married-civ-spouse,exec-managerial,husband,asian-pac-islander,male,0.0,0.0,3.0,VNM,vietnam,0.0

In [3]:
data_test = pandas.read_csv('../dataset/high_salary.test.csv').set_index('id')
data_test

,social-security-number,house-number,age-group,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native-country-code,native-country,label
id,,,,,,,,,,,,,,,,,,
12849,335086368.0,4170.0,1.0,private,509500.0,bachelors,13.0,never-married,tech-support,not-in-family,white,female,2.0,0.0,2.0,USA,united-states,1.0
1460,732733728.0,5442.0,0.0,private,243368.0,preschool,1.0,never-married,farming-fishing,not-in-family,white,male,0.0,0.0,3.0,MEX,mexico,0.0
13594,807579036.0,7659.0,2.0,private,144524.0,hs-grad,9.0,divorced,machine-op-inspct,unmarried,black,female,0.0,0.0,2.0,USA,united-states,0.0
14400,201637967.0,4318.0,3.0,private,150975.0,hs-grad,9.0,divorced,machine-op-inspct,not-in-family,amer-indian-eskimo,female,NaN,0.0,2.0,USA,united-states,0.0
14333,758267678.0,8392.0,2.0,private,136419.0,hs-grad,9.0,married-civ-spouse,craft-repair,husband,white,male,0.0,0.0,3.0,USA,united-states,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
981,928104737.0,5063.0,1.0,private,346736.0,assoc-acdm,12.0,never-married,exec-managerial,own-child,white,female,0.0,0.0,3.0,USA,united-states,0.0
2952,516722538.0,6064.0,2.0,private,54422.0,assoc-acdm,12.0,married-civ-spouse,prof-specialty,wife,white,female,0.0,0.0,2.0,USA,united-states,1.0
9470,197607445.0,1195.0,4.0,state-gov,124971.0,doctorate,16.0,married-civ-spouse,prof-specialty,husband,white,male,0.0,0.0,2.0,NaN,NaN,1.0
16559,970701590.0,3671.0,4.0,local-gov,147707.0,hs-grad,9.0,widowed,farming-fishing,unmarried,white,male,0.0,4.0,2.0,USA,united-states,0.0
27733,814850654.0,862.0,2.0,self-emp-not-inc,366483.0,hs-grad,9.0,married-civ-spouse,farming-fishing,husband,white,male,0.0,0.0,2.0,MEX,mexico,0.0

In [4]:
data_live = pandas.read_csv('../dataset/high_salary.live.csv').set_index('id')
data_live

,social-security-number,house-number,age-group,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native-country-code,native-country
id,,,,,,,,,,,,,,,,,
6111,565712576.0,9337.0,0.0,private,287357.0,11th,7.0,married-civ-spouse,protective-serv,husband,white,male,0.0,0.0,2.0,USA,united-states
11214,329599477.0,6457.0,1.0,private,167558.0,hs-grad,9.0,never-married,sales,unmarried,white,female,0.0,0.0,1.0,MEX,mexico
5554,222432362.0,189.0,4.0,private,27385.0,hs-grad,9.0,married-civ-spouse,exec-managerial,husband,white,male,0.0,0.0,3.0,USA,united-states
25131,209882990.0,2048.0,2.0,local-gov,153976.0,masters,14.0,married-civ-spouse,prof-specialty,husband,white,male,0.0,0.0,2.0,USA,united-states
14324,936607310.0,8185.0,3.0,private,20956.0,hs-grad,9.0,married-civ-spouse,craft-repair,husband,white,male,0.0,0.0,2.0,USA,united-states
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25998,331613078.0,6349.0,4.0,private,117898.0,bachelors,13.0,married-civ-spouse,exec-managerial,husband,white,male,0.0,0.0,3.0,USA,united-states
8375,353499588.0,5768.0,4.0,private,298546.0,hs-grad,9.0,married-civ-spouse,farming-fishing,husband,white,male,0.0,0.0,4.0,USA,united-states
13888,604365500.0,6286.0,1.0,private,36340.0,11th,7.0,divorced,other-service,unmarried,white,female,0.0,0.0,1.0,USA,united-states
4159,258361593.0,5369.0,1.0,private,173473.0,masters,14.0,married-civ-spouse,prof-specialty,husband,asian-pac-islander,male,0.0,0.0,2.0,USA,united-states
9658,987175237.0,212.0,0.0,NaN,199426.0,some-college,10.0,never-married,NaN,not-in-family,white,female,0.0,0.0,2.0,USA,united-states

In [5]:
data_train.dtypes

social-security-number    float64
house-number              float64
age-group                 float64
workclass                  object
fnlwgt                    float64
education                  object
education-num             float64
marital-status             object
occupation                 object
relationship               object
race                       object
sex                        object
capitalgain               float64
capitalloss               float64
hoursperweek              float64
native-country-code        object
native-country             object
label                     float64
dtype: object

In [6]:
categorical_features = [
    'workclass', 
    'education', 
    'marital-status', 
    'occupation',
    'relationship', 
    'race', 
    'sex',
    'native-country-code', 
    'native-country', 
]

for feature in categorical_features:
    possible_values = data_train[feature].unique()
    print(f"{feature:20s} {possible_values.size:2d} {possible_values}")

workclass             9 ['self-emp-not-inc' 'private' nan 'self-emp-inc' 'local-gov' 'federal-gov'
 'state-gov' 'never-worked' 'without-pay']
education            17 ['prof-school' 'hs-grad' 'some-college' '1st-4th' 'masters' 'bachelors'
 '11th' 'assoc-acdm' 'assoc-voc' 'doctorate' '7th-8th' '10th' '9th'
 '5th-6th' '12th' nan 'preschool']
marital-status        8 ['never-married' 'married-civ-spouse' 'separated' 'divorced'
 'married-af-spouse' 'widowed' 'married-spouse-absent' nan]
occupation           15 ['prof-specialty' 'sales' 'exec-managerial' 'craft-repair'
 'machine-op-inspct' nan 'other-service' 'handlers-cleaners'
 'tech-support' 'transport-moving' 'farming-fishing' 'priv-house-serv'
 'adm-clerical' 'protective-serv' 'armed-forces']
relationship          7 ['not-in-family' 'husband' 'other-relative' 'wife' 'own-child' 'unmarried'
 nan]
race                  6 ['white' 'amer-indian-eskimo' 'black' 'asian-pac-islander' 'other' nan]
sex                   3 ['male' 'female' nan]
native-country-code  41 ['USA' 'MEX' 'GBR' 'ITA' 'SLV' nan 'CAN' 'DUE' 'JAM' 'ECU' 'JPN' 'DOM'
 'IRL' 'PHL' 'CUB' 'VNM' 'GTM' 'TWN' 'HUN' 'FRA' 'UMI' 'HKG' 'KHM' 'IRN'
 'CHN' 'COL' 'PRI' 'YUG' 'POL' 'GRC' 'TTO' 'IND' 'NIC' 'ZAF' 'PRT' 'HND'
 'THA' 'HTI' 'LAO' 'PER' 'NLD']
native-country       42 ['united-states' 'mexico' 'england' 'italy' 'el-salvador' nan 'canada'
 'germany' 'jamaica' 'ecuador' 'japan' 'dominican-republic' 'ireland'
 'philippines' 'cuba' 'vietnam' 'guatemala' 'taiwan' 'hungary' 'france'
 'outlying-us(guam-usvi-etc)' 'hong' 'cambodia' 'iran' 'china' 'columbia'
 'puerto-rico' 'yugoslavia' 'poland' 'greece' 'trinadad&tobago' 'india'
 'nicaragua' 'south' 'portugal' 'honduras' 'thailand' 'laos' 'peru'
 'holand-netherlands' 'haiti' 'scotland']

In [7]:
data_train['label'].value_counts()

label
0.0    9102
1.0    6573
Name: count, dtype: int64

In [8]:
data_test['label'].value_counts()

label
0.0    3033
1.0    2192
Name: count, dtype: int64

In [9]:
data_train.isna().sum(axis='index')

social-security-number     11
house-number               18
age-group                   6
workclass                 792
fnlwgt                     16
education                  15
education-num              12
marital-status             20
occupation                791
relationship               14
race                       13
sex                        14
capitalgain                17
capitalloss                14
hoursperweek               18
native-country-code       301
native-country            302
label                       0
dtype: int64

In [10]:
data_test.isna().sum(axis='index')

social-security-number      3
house-number                9
age-group                   7
workclass                 265
fnlwgt                      7
education                   5
education-num               2
marital-status              3
occupation                263
relationship                7
race                        9
sex                         8
capitalgain                 6
capitalloss                 7
hoursperweek                3
native-country-code        98
native-country             96
label                       0
dtype: int64

In [11]:
data_train = data_train.dropna()

In [12]:
data_train.isna().sum(axis='index')

social-security-number    0
house-number              0
age-group                 0
workclass                 0
fnlwgt                    0
education                 0
education-num             0
marital-status            0
occupation                0
relationship              0
race                      0
sex                       0
capitalgain               0
capitalloss               0
hoursperweek              0
native-country-code       0
native-country            0
label                     0
dtype: int64

In [13]:
data_test = data_test.dropna()

In [14]:
data_test.isna().sum(axis='index')

social-security-number    0
house-number              0
age-group                 0
workclass                 0
fnlwgt                    0
education                 0
education-num             0
marital-status            0
occupation                0
relationship              0
race                      0
sex                       0
capitalgain               0
capitalloss               0
hoursperweek              0
native-country-code       0
native-country            0
label                     0
dtype: int64

In [15]:
categorical_cols = data_live.select_dtypes(include='object').columns
numerical_cols = data_live.select_dtypes(include='number').columns

In [16]:
imputer_num = SimpleImputer(strategy='median')
data_live[numerical_cols] = imputer_num.fit_transform(data_live[numerical_cols])

In [17]:
imputer_cat = SimpleImputer(strategy='most_frequent')
data_live[categorical_cols] = imputer_cat.fit_transform(data_live[categorical_cols])

In [18]:
ordinal_features = ["education", "age-group", "hoursperweek", "education-num"]

In [19]:
ordinal_mapping = [sorted(data_train[feature].dropna().unique()) for feature in ordinal_features]

In [20]:
print("")
for f, m in zip(ordinal_features, ordinal_mapping):
    print(f"{f}: {m}")

education: ['10th', '11th', '12th', '1st-4th', '5th-6th', '7th-8th', '9th', 'assoc-acdm', 'assoc-voc', 'bachelors', 'doctorate', 'hs-grad', 'masters', 'preschool', 'prof-school', 'some-college']
age-group: [0.0, 1.0, 2.0, 3.0, 4.0]
hoursperweek: [0.0, 1.0, 2.0, 3.0, 4.0]
education-num: [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0]

In [21]:
ordinal_encoder = OrdinalEncoder(categories=ordinal_mapping)

In [22]:
data_train_ordinal = pandas.DataFrame(
    ordinal_encoder.fit_transform(data_train[ordinal_features]),
    columns=ordinal_features,
    index=data_train.index
)

In [23]:
data_test_ordinal = pandas.DataFrame(
    ordinal_encoder.transform(data_test[ordinal_features]),
    columns=ordinal_features,
    index=data_test.index
)
data_test_ordinal

       education  age-group  hoursperweek  education-num
id
12849        9.0        1.0           2.0           12.0
1460        13.0        0.0           3.0            0.0
13594       11.0        2.0           2.0            8.0
14333       11.0        2.0           3.0            8.0
10595        9.0        2.0           4.0           12.0
...          ...        ...           ...            ...
16929       11.0        0.0           2.0            8.0
981          7.0        1.0           3.0           11.0
2952         7.0        2.0           2.0           11.0
16559       11.0        4.0           2.0            8.0
27733       11.0        2.0           2.0            8.0

[4792 rows x 4 columns]

In [24]:
data_live_ordinal = pandas.DataFrame(
    ordinal_encoder.transform(data_live[ordinal_features]),
    columns=ordinal_features,
    index=data_live.index
)
data_live_ordinal

       education  age-group  hoursperweek  education-num
id
6111         1.0        0.0           2.0            6.0
11214       11.0        1.0           1.0            8.0
5554        11.0        4.0           3.0            8.0
25131       12.0        2.0           2.0           13.0
14324       11.0        3.0           2.0            8.0
...          ...        ...           ...            ...
25998        9.0        4.0           3.0           12.0
8375        11.0        4.0           4.0            8.0
13888        1.0        1.0           1.0            6.0
4159        12.0        1.0           2.0           13.0
9658        15.0        0.0           2.0            9.0

[6967 rows x 4 columns]

In [25]:
nominal_features = [
    'workclass',
    'marital-status',
    'occupation',
    'relationship',
    'race',
    'sex',
    'native-country-code',
    'native-country',
]

In [26]:
onehot_encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
onehot_encoder.fit(data_train[nominal_features])

OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [27]:
data_train_nominal = pandas.DataFrame(
    onehot_encoder.transform(data_train[nominal_features]),
    columns=onehot_encoder.get_feature_names_out(nominal_features),
    index=data_train.index
)

In [28]:
data_test_nominal = pandas.DataFrame(
    onehot_encoder.transform(data_test[nominal_features]),
    columns=onehot_encoder.get_feature_names_out(nominal_features),
    index=data_test.index
)

In [29]:
data_live_nominal = pandas.DataFrame(
    onehot_encoder.transform(data_live[nominal_features]),
    columns=onehot_encoder.get_feature_names_out(nominal_features),
    index=data_live.index
)

In [30]:
numerical_features = [
    'fnlwgt',
    'capitalgain',
    'capitalloss',
]

In [31]:
scaler = StandardScaler()
scaler.fit(data_train[numerical_features])

StandardScaler()

In [32]:
data_train_numerical_features = pandas.DataFrame(
    scaler.transform(data_train[numerical_features]),
    columns=numerical_features,
    index=data_train.index
)
data_train_numerical_features

         fnlwgt  capitalgain  capitalloss
id
2103   1.395884    -0.330368     6.058927
14649 -0.877088    -0.330368    -0.231477
7379  -0.594928    -0.330368    -0.231477
24479 -1.353541    -0.330368    -0.231477
19532  2.042650    -0.330368    -0.231477
...         ...          ...          ...
8695  -1.409555    -0.330368    -0.231477
2192  -0.824666     1.774050    -0.231477
8250   1.210367    -0.330368    -0.231477
18511  2.798762    -0.330368    -0.231477
16074 -1.099555    -0.330368    -0.231477

[14396 rows x 3 columns]

In [33]:
data_test_numerical_features = pandas.DataFrame(
    scaler.transform(data_test[numerical_features]),
    columns=numerical_features,
    index=data_test.index
)
data_test_numerical_features

         fnlwgt  capitalgain  capitalloss
id
12849  3.062337     1.774050    -0.231477
1460   0.512789    -0.330368    -0.231477
13594 -0.434137    -0.330368    -0.231477
14333 -0.511783    -0.330368    -0.231477
10595 -1.012607    -0.330368    -0.231477
...         ...          ...          ...
16929  0.004876    -0.330368    -0.231477
981    1.503056    -0.330368    -0.231477
2952  -1.297315    -0.330368    -0.231477
16559 -0.403644    -0.330368     6.058927
27733  1.692232    -0.330368    -0.231477

[4792 rows x 3 columns]

In [34]:
data_live_numerical_features = pandas.DataFrame(
    scaler.transform(data_live[numerical_features]),
    columns=numerical_features,
    index=data_live.index
)
data_live_numerical_features

         fnlwgt  capitalgain  capitalloss
id
6111   0.934204    -0.330368    -0.231477
11214 -0.213471    -0.330368    -0.231477
5554  -1.556330    -0.330368    -0.231477
25131 -0.343587    -0.330368    -0.231477
14324 -1.617920    -0.330368    -0.231477
...         ...          ...          ...
25998 -0.689215    -0.330368    -0.231477
8375   1.041395    -0.330368    -0.231477
13888 -1.470541    -0.330368    -0.231477
4159  -0.156806    -0.330368    -0.231477
9658   0.091824    -0.330368    -0.231477

[6967 rows x 3 columns]

In [35]:
label_encoder = LabelEncoder()
data_train_label = pandas.DataFrame(
    label_encoder.fit_transform(data_train["label"]),
    columns=["label"],
    index=data_train.index
)

In [36]:
data_test_label = pandas.DataFrame(
    label_encoder.transform(data_test["label"]),
    columns=["label"],
    index=data_test.index
)

In [37]:
data_train_final = data_train_numerical_features.join(data_train_ordinal).join(data_train_nominal).join(data_train_label)
data_test_final  = data_test_numerical_features.join(data_test_ordinal).join(data_test_nominal).join(data_test_label)
data_live_final  = data_live_numerical_features.join(data_live_ordinal).join(data_live_nominal)

In [38]:
data_train_final.to_csv("./data/features.train.csv")
data_test_final.to_csv("./data/features.test.csv")
data_live_final.to_csv("./data/features.live.csv")